import type { Diagram } from "../../../lib/diagram.ts";

export default {
	caption: "Fig. 03 — runtime layers",
	description:
		"Sketch: a Flutter UI for Android, iOS, macOS, Windows, and Linux talks through Buf-managed Protobuf contracts to a Rust runtime with an agent core, AI and TTS provider adapters, and an encrypted store built on CAS and SQLCipher.",
	height: 300,
	scenario: "layers",
	width: 340,
	items: [
		{ group: "ui", h: 40, label: "Flutter UI", step: 1, type: "box", w: 316, x: 12, y: 10 },
		{
			anchor: "middle",
			group: "ui",
			kind: "mono",
			step: 1,
			text: "android · ios · macos · windows · linux",
			type: "text",
			x: 170,
			y: 68,
		},
		{
			anchor: "middle",
			group: "contracts",
			kind: "small",
			step: 2,
			text: "Protobuf contracts · Buf",
			type: "text",
			x: 170,
			y: 91,
		},
		{
			dashed: true,
			group: "contracts",
			points: [
				[12, 98],
				[328, 98],
			],
			step: 2,
			type: "line",
		},
		{
			group: "contracts",
			points: [
				[40, 76],
				[40, 116],
			],
			step: 2,
			type: "arrow",
		},
		{
			group: "contracts",
			points: [
				[300, 116],
				[300, 76],
			],
			step: 2,
			type: "arrow",
		},
		{ group: "runtime", h: 132, r: 12, step: 3, type: "frame", w: 316, x: 12, y: 120 },
		{ group: "runtime", kind: "small", step: 3, text: "Rust runtime", type: "text", x: 22, y: 142 },
		{
			group: "runtime",
			h: 56,
			label: "Agent",
			step: 3,
			sub: "core services",
			type: "box",
			w: 96,
			x: 22,
			y: 156,
		},
		{
			group: "runtime",
			h: 56,
			label: "Providers",
			step: 3,
			sub: "AI · TTS",
			type: "box",
			w: 96,
			x: 122,
			y: 156,
		},
		{
			fill: true,
			group: "runtime",
			h: 56,
			label: "Store",
			step: 3,
			sub: "CAS · SQLCipher",
			type: "box",
			w: 96,
			x: 222,
			y: 156,
		},
		{
			anchor: "end",
			kind: "hand",
			step: 4,
			text: "local-first, encrypted at rest",
			type: "text",
			x: 332,
			y: 290,
		},
		{
			accent: true,
			points: [
				[300, 272],
				[292, 244],
				[276, 216],
			],
			step: 4,
			type: "arrow",
		},
	],
} satisfies Diagram;
